### ISSUE TITLE
Test URLs don't escape +addresses properly

### ISSUE THREAD

**Issue by saulrh** [mbrt/gmailctl#46]
config.jsonnet snippet for filter demonstrating issue:
```
    {
      filter: { from: "foo+bar@example.org" },
      actions: { labels: ['example'] },
    }
```
`gmailctl debug` output:
```yaml
# Search: from:foo+bar@example.org
# URL: https://mail.google.com/mail/u/0/#search/from:foo+bar@example.org
filter:
  from: foo+bar@example.org
actions:
  labels:
  - example
```
The unescaped + in the address is interpreted as a space in the URL, taking you to a search for `from:foo bar@example.org`.
